version: '3.8'
name: 2b-imaging
services:
  client-backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: client_backend
    restart: always
    ports:
      - 4200:4200
    volumes:
      - ../backend/patientimages:/app/patientimages
    networks:
      - 'apiNetwork'

  client-frontend:
    # depends_on:
    #   - client_backend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: client_frontend
    restart: always
    ports:
      - 3000:3000
    networks:
      - 'apiNetwork'

networks:
  apiNetwork:
